### ISSUE TITLE
Getting error on self signed certificates

### ISSUE THREAD

**Issue by mrdvt92** [bartbutenaers/node-red-contrib-certificate-grabber#1]
I get the error "Cannot get certificate due to error: Error: getaddrinfo ENOTFOUND unifi.local".  

I have this certificate loaded on my browser but not in my Node-Red Docker.  It would be nice to still be able to get the certificate daysRemaining even when using self signed certificates without needing to install all of them inside the node-red instance as well.

This command with openssl supports self signed certificates so it's possible.

```
$ host=unifi.local; port=443; /usr/bin/openssl s_client -servername $host -connect $host:$port </dev/null 2>/dev/null | /usr/bin/openssl x509 -noout -enddate 2> /dev/null
notAfter=Mar 25 14:16:59 2024 GMT
```

**Comment by mrdvt92** [comment]
This issue was that the Docker DNS could not resolve .local addresses correctly.  This issue has been worked around until I figure out the DNS configuration inside Docker.

**Comment by bartbutenaers** [comment]
Hi @mrdvt92,

Well to be honest I didn't test with self signed certificates.  Do I understand correctly that this node works correctly for self signed nodes, after your dns workaround?

Thanks for your feedback!  
That saves me some time for not having to test it myself...
Bart

**Comment by mrdvt92** [comment]
So, I'm not 100% sure what the DNS issue is but it is an Alpine Linux issue where it does not use the "search" when a host name has a dot in it.  So, if you have a "host.local.tld.com" host name that can be resolved by tld.com a lookup for "host.local" fails on Alpine Linux but works on others that I successfully tested pihole, CentOS, Fedora. 

This is the bug https://github.com/gliderlabs/docker-alpine/issues/539#issuecomment-576284802

Unfortunately, Node-Red selected Alpine Linux as it's Docker base.

To work around, I'm using the full DNS name which does NOT match the SSL cert name.
